"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Load environment variables
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-q_&t!ifun-@0yl@_8gu=%c&!cg2w@6q01icvcm%bfkwb4&knd+")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "followupper",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "followupper.middleware.CSRFExemptAPI",  # Exempt API routes from CSRF (must be before CsrfViewMiddleware)
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "followupper.middleware.RequestLoggingMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR.parent / "followupper.db"}',
        conn_max_age=600
    )
}

# Add connection settings for PostgreSQL
# Railway and most cloud PostgreSQL services require SSL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,  # 10 second timeout
        'sslmode': 'require',  # Railway requires SSL
    }

# Print database URL on startup (mask password for security)
# Use print() because logging isn't initialized when settings.py loads
database_url_env = os.getenv('DATABASE_URL')
if database_url_env:
    # Mask password in environment URL
    if '@' in database_url_env and '://' in database_url_env:
        parts = database_url_env.split('://')
        if len(parts) == 2:
            scheme = parts[0]
            rest = parts[1]
            if '@' in rest:
                auth_part, host_part = rest.split('@', 1)
                if ':' in auth_part:
                    user, password = auth_part.split(':', 1)
                    masked_env_url = f"{scheme}://{user}:{'*' * len(password)}@{host_part}"
                    print(f"Database URL: {masked_env_url}")
                else:
                    print(f"Database URL: {scheme}://{auth_part}@***")
            else:
                print(f"Database URL: {scheme}://***")
        else:
            print(f"Database URL: {database_url_env}")
    else:
        print(f"Database URL: {database_url_env}")
else:
    # No DATABASE_URL env var, construct from parsed config
    db_config = DATABASES['default']
    db_engine = db_config.get('ENGINE', '')

    if db_engine == 'django.db.backends.sqlite3':
        # SQLite - show the path
        db_name = db_config.get('NAME', '')
        print(f"Database URL: sqlite:///{db_name}")
    else:
        # Other databases - construct URL and mask password
        db_name = db_config.get('NAME', '')
        db_user = db_config.get('USER', '')
        db_password = db_config.get('PASSWORD', '')
        db_host = db_config.get('HOST', 'localhost')
        db_port = db_config.get('PORT', '')

        # Map Django engine to URL scheme
        engine_to_scheme = {
            'django.db.backends.postgresql': 'postgresql',
            'django.db.backends.postgresql_psycopg2': 'postgresql',
            'django.db.backends.mysql': 'mysql',
            'django.db.backends.sqlite3': 'sqlite',
        }
        scheme = engine_to_scheme.get(db_engine, db_engine.split('.')[-1])

        # Construct URL with masked password
        masked_password = '*' * len(db_password) if db_password else ''

        if db_port:
            db_url_display = f"{scheme}://{db_user}:{masked_password}@{db_host}:{db_port}/{db_name}"
        else:
            db_url_display = f"{scheme}://{db_user}:{masked_password}@{db_host}/{db_name}"

        print(f"Database URL: {db_url_display}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',  # For file uploads
        'rest_framework.parsers.FormParser',  # For form data
    ],
    'DEFAULT_PAGINATION_CLASS': None,
    # Allow unauthenticated access for backward compatibility (data is global, not user-specific)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# CORS settings
# Read from environment variable - comma-separated list of origins
# Example: CORS_ALLOWED_ORIGINS=http://localhost:4000,https://your-app.netlify.app
cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:4000,http://127.0.0.1:4000')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]

# Must be False when using credentials - can't use wildcard with credentials
CORS_ALLOW_ALL_ORIGINS = False

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF settings for API - exempt all /api/ routes since this is an API
# (CSRF is for server-rendered forms, not REST APIs)

# Exempt API views from CSRF (REST Framework handles auth differently)
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'None'  # Allow cross-domain cookies
CSRF_COOKIE_SECURE = True  # Required when SameSite=None (HTTPS only)

# Session cookie settings for cross-domain authentication
SESSION_COOKIE_SAMESITE = 'None'  # Allow cross-domain cookies
SESSION_COOKIE_SECURE = True  # Required when SameSite=None (HTTPS only)
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attLaxs

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'followupper': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
