# Generated by Django 5.2.8 on 2025-11-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("recurring", "Recurring"),
                            ("sequence", "Sequence"),
                            ("one_off", "One-Off"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("default_frequency_days", models.IntegerField(default=7)),
                ("frequency_type", models.CharField(blank=True, max_length=20)),
                ("send_day", models.CharField(blank=True, max_length=10)),
                ("send_time", models.CharField(default="09:00", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("message_template", models.TextField(blank=True)),
                (
                    "start_immediately",
                    models.CharField(default="scheduled", max_length=20),
                ),
                ("total_steps", models.IntegerField(default=0)),
                ("total_duration_days", models.IntegerField(default=0)),
                ("next_message_override", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "campaigns",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "codementor_username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "platform_preference",
                    models.CharField(default="email", max_length=50),
                ),
                ("last_contact_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contacts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "message_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("credentials", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "platform_credentials",
            },
        ),
        migrations.CreateModel(
            name="ScheduledFollowup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("platform", models.CharField(db_index=True, max_length=50)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_followups",
                        to="followupper.contact",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_followups",
                        to="followupper.messagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_followups",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="CampaignStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message_template", models.TextField()),
                ("delay_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_steps",
                        to="followupper.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_steps",
                "ordering": ["campaign", "step_number"],
                "unique_together": {("campaign", "step_number")},
            },
        ),
        migrations.CreateModel(
            name="CampaignAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("blacklisted", "Blacklisted"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("custom_frequency_days", models.IntegerField(blank=True, null=True)),
                ("custom_send_time", models.CharField(blank=True, max_length=10)),
                ("custom_timezone", models.CharField(blank=True, max_length=50)),
                ("current_step", models.IntegerField(default=0)),
                ("next_send_date", models.DateTimeField(blank=True, null=True)),
                ("custom_message_override", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_assignments",
                        to="followupper.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_assignments",
                        to="followupper.contact",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_assignments",
                "unique_together": {("campaign", "contact")},
            },
        ),
    ]
