# Generated by Django 5.2.8 on 2025-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message_chains",
            field=models.TextField(blank=True),
        ),
    ]
