# Generated by Django 5.2.8 on 2025-11-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0002_contact_message_chains"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="timezone",
            field=models.CharField(blank=True, default="UTC", max_length=50),
        ),
    ]
