# Generated by Django 5.2.8 on 2025-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0003_contact_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, default="UTC", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
    ]
