# Generated by Django 5.2.8 on 2025-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0004_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "check_interval",
                    models.IntegerField(
                        default=15,
                        help_text="Check interval in minutes (minimum 1 minute)",
                    ),
                ),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "timezone",
                    models.CharField(blank=True, default="UTC", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Automation Settings",
                "verbose_name_plural": "Automation Settings",
                "db_table": "automation_settings",
            },
        ),
    ]
