# Generated by Django 5.2.8 on 2025-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0005_automationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="footer",
            field=models.TextField(
                blank=True,
                help_text="Default footer/signature to append to all messages",
            ),
        ),
    ]
