# Generated by Django 5.2.8 on 2025-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0006_usersettings_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message_history",
            field=models.TextField(blank=True),
        ),
    ]
