# Generated by Django 5.2.8 on 2025-11-09 21:58

import django.db.models.deletion
import json
from django.db import migrations, models


def convert_platform_preference_to_json(apps, schema_editor):
    """Convert platform_preference from string to JSON array format before field change."""
    Contact = apps.get_model('followupper', 'Contact')
    
    for contact in Contact.objects.all():
        if not contact.platform_preference:
            # Store as JSON string temporarily (will be converted to list by JSONField)
            contact.platform_preference = '[]'
        elif isinstance(contact.platform_preference, str):
            # Check if it's already JSON
            try:
                parsed = json.loads(contact.platform_preference)
                if isinstance(parsed, list):
                    # Already valid JSON array, keep it
                    continue
            except (json.JSONDecodeError, TypeError):
                pass
            
            # Not JSON, convert legacy format
            if contact.platform_preference == 'both':
                contact.platform_preference = '["email", "codementor"]'
            elif contact.platform_preference in ['email', 'codementor']:
                contact.platform_preference = json.dumps([contact.platform_preference])
            else:
                contact.platform_preference = '[]'
        contact.save(update_fields=['platform_preference'])


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0007_contact_message_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="message_chains",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="message_history",
        ),
        # Convert data BEFORE changing field type
        migrations.RunPython(
            convert_platform_preference_to_json,
            migrations.RunPython.noop,  # No reverse needed - field change handles it
        ),
        migrations.AlterField(
            model_name="contact",
            name="platform_preference",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="MessageSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timing_type", models.CharField(default="specific", max_length=20)),
                ("chain_start_date", models.DateField(blank=True, null=True)),
                ("chain_start_time", models.TimeField(blank=True, null=True)),
                (
                    "chain_timezone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sequences",
                        to="followupper.contact",
                    ),
                ),
            ],
            options={
                "db_table": "message_sequences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("platforms", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("send_date", models.DateField(blank=True, db_index=True, null=True)),
                ("send_time", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("frequency_days", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="followupper.campaign",
                    ),
                ),
                (
                    "campaign_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="followupper.campaignassignment",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="followupper.contact",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="followupper.messagesequence",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contact", "status"], name="messages_contact_e17c09_idx"
                    ),
                    models.Index(
                        fields=["status", "send_date", "send_time"],
                        name="messages_status_0b4bfe_idx",
                    ),
                    models.Index(
                        fields=["sequence", "order"], name="messages_sequenc_94ea7b_idx"
                    ),
                ],
            },
        ),
    ]
