# Generated by Django 5.2.8 on 2025-11-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0008_remove_contact_message_chains_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationsettings",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
