# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0009_alter_automationsettings_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="email_message_id",
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
