# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0010_message_email_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="preferred_name",
            field=models.CharField(blank=True, help_text="Preferred name/nickname to use instead of first name", max_length=255),
        ),
    ]

