# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0011_contact_preferred_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="gender",
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
    ]

