# Generated by Django 5.2.8 on 2025-11-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0017_interestsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_favorite",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this contact is marked as favorite",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Source of the contact (e.g., 'codementor', 'manual', 'csv')",
                max_length=100,
            ),
        ),
    ]
