# Generated by Django 5.2.8 on 2025-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0018_contact_is_favorite_contact_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="codementor_max_concurrent",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of Codementor messages that can be sent at the same time",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="codementor_send_interval",
            field=models.IntegerField(
                default=5,
                help_text="Interval in seconds between sending Codementor messages",
            ),
        ),
    ]
