# Generated by Django 5.2.8 on 2025-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0019_usersettings_codementor_max_concurrent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignassignment",
            name="custom_send_day",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
