# Generated by Django 5.2.8 on 2025-11-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0020_campaignassignment_custom_send_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="subject_template",
            field=models.CharField(
                blank=True,
                help_text="Subject template for recurring campaigns (supports template variables)",
                max_length=500,
            ),
        ),
    ]
