# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followupper", "0021_campaign_subject_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="footer_template",
            field=models.TextField(
                blank=True,
                help_text="Footer/signature template for recurring campaigns (supports template variables, email only)",
            ),
        ),
    ]

