"""update_platform_credentials_to_plain_json

Revision ID: d98c3aa6ba05
Revises: eccd7e238699
Create Date: 2025-10-23 13:21:00.065538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98c3aa6ba05'
down_revision = 'eccd7e238699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_credentials', sa.Column('credentials', sa.Text(), nullable=False))
    op.drop_column('platform_credentials', 'encrypted_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_credentials', sa.Column('encrypted_credentials', sa.TEXT(), nullable=False))
    op.drop_column('platform_credentials', 'credentials')
    # ### end Alembic commands ###
