"""remove_platform_from_message_templates

Revision ID: eccd7e238699
Revises: 0002
Create Date: 2025-10-23 11:08:17.388680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccd7e238699'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_templates_platform'), table_name='message_templates')
    op.drop_column('message_templates', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_templates', sa.Column('platform', sa.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_message_templates_platform'), 'message_templates', ['platform'], unique=False)
    # ### end Alembic commands ###
